namespace: pr-13
deploymentName: challenge-app-pr-13
serviceName: challenge-app-pr-13
image:
  repository: ghcr.io/federicomameli1/challenge-app
  tag: d2ce6d47c124e335d8daad1651bcaeba49c124c3
  pullPolicy: IfNotPresent
