namespace: pr-16
deploymentName: challenge-app-pr-16
serviceName: challenge-app-pr-16
image:
  repository: ghcr.io/federicomameli1/challenge-app
  tag: d2e3c466bdd825d1ebd42e36728b8fb9264cf750
  pullPolicy: IfNotPresent
